### PR TITLE
Created after_prepare.js hook to add white-listed urls to the manifes…

### PR DESCRIPTION
**Pull request by mac89**
Created after_prepare.js hook to add white-listed urls to the manifest files.

Fixed onNavigation not able to be called.
Improved navigation failure handling.

### CODE REVIEW

**Comment by jraats** [comment]
after_prepare.js
Is there a reason why the regex is:
var regexConfigFile = /([\s\S]*)(<\/Application>)/g;
and not for example:
var regexConfigFile = /(<Application(?:[\s\S]*)>)([\s\S]*)(<\/Application>)/g;
This only replaces the content between < Application> and </ Application>
Regex is complexer, but the replace is smaller. Don't know which is faster.

WindowsWebviewProxy.js  contains a strange layout (no enters?)
WindowsWebviewProxy.js Why is only on line 168 t/m 188 a check if fail is a fuction and not also on 192 and 203
Maybe also use onFail(e)?

**Review by jraats — CHANGES_REQUESTED** [review]
after_prepare.js
Is there a reason why the regex is:
var regexConfigFile = /([\s\S]*)(<\/Application>)/g;
and not for example:
var regexConfigFile = /(<Application(?:[\s\S]*)>)([\s\S]*)(<\/Application>)/g;
This only replaces the content between <Application> and </Application>
Regex is complexer, but the replace is smaller. Don't know which is faster.

WindowsWebviewProxy.js  contains a strange layout (no enters?)
WindowsWebviewProxy.js Why is only on line 168 t/m 188 a check if fail is a fuction and not also on 192 and 203
Maybe also use onFail(e)?

**Comment by mac89** [comment]
Changing the regex seems to make no difference speed wise.

**Comment by rcolpaert** [comment]
Some methods could do with a comment, but the rest looks fine.

**Pull request merged**
